#!/bin/sh

# Register with gnome-session so that it does not kill the whole session thinking it is dead.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.RegisterClient "string:qtile-gnome" "string:$DESKTOP_AUTOSTART_ID"
fi

qtile start

# Close session when Qtile exits.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.Logout "uint32:1"
fi
