#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="Qtile-GNOME-Flashback:GNOME-Flashback:GNOME"
fi

exec gnome-session --builtin --session=qtile-gnome-flashback --disable-acceleration-check "$@"
